# Generated by Django 4.2.1 on 2023-06-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_pokemon_breed_alter_pokemon_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='cat',
            new_name='pokemon',
        ),
    ]
